#!/bin/bash

sudo docker stop node-red
sudo certbot renew
sudo cp /etc/letsencrypt/live/betatest.eupry.com/privkey.pem ~/eupry-test-environment/server/certs
sudo cp /etc/letsencrypt/live/betatest.eupry.com/fullchain.pem ~/eupry-test-environment/server/certs
sudo docker start node-red
